export class Emisor{
    idEmisor !: number;
    codEmisor !: string;
    codIDCCliente !: number;
    nomEmisor !: string;
    codTipoEmisor !: string;
    detalle !: string;
    flgEmiReport !: boolean;
    flgOrgaMulti !: boolean;
    ambito !: string;
    codBloomberg !: string;
    flgContratoMarco !: boolean;
    flgContratoEspecifico !: boolean;
    numThresHold !: number;
    codSBS !: string;
    codRUC !: string;
    codFuente !: string;
    codTipoEmisorAnx8 !: string;
    idPais !: string;
}